name: Node.js CI

on:
  push:
    branches:
      - main
      - develop
      - staging
  pull_request:
    branches:
      - main
      - develop
      - staging

jobs:
  test:
    needs: [start-noti]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Use Node.js v14.17
        uses: actions/setup-node@v2
        with:
          node-version: 14.17
      - run: yarn install
      - run: yarn test
